import React, { useState, useEffect } from 'react';
import axios from 'axios';
import MainLayout from '../../component/Main/MainLayout';
import { DataGrid } from '@mui/x-data-grid';
import Button from '@mui/material/Button';
import { ClipLoader } from 'react-spinners';
import { Box } from '@mui/material';
import { URLng } from '../../API/constant';
import emailjs from 'emailjs-com';
import { useDispatch } from 'react-redux';
import {
  accpeting,
  loging,
  registering,
} from '../../Redux/Slices/userStatusSlice';

function AcceptStudent() {
  const [rows, setRows] = useState([
    {
      id: 3,
      name: 'نتالاىبتبيبب',
      english_name: 'mohamed',
      age: 68,
      SSN: '5024825737836781',
      email: 'mmerna78@saykocak.com',
      account: '',
      phone: '556564655678',
      nationality: null,
      religion: null,
      job: null,
      address: 'hgjhgkk',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 2,
      created_at: '2024-05-09T11:16:28.000000Z',
      updated_at: '2024-05-09T11:16:28.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 4,
      name: 'نتالاىبتبيبب',
      english_name: 'mohamed',
      age: 68,
      SSN: '5024825737836781',
      email: 'mmernax78@saykocak.com',
      account: null,
      phone: '556564655678',
      nationality: null,
      religion: null,
      job: null,
      address: 'hgjhgkk',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 3,
      created_at: '2024-05-09T21:27:22.000000Z',
      updated_at: '2024-05-09T21:27:22.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 5,
      name: 'Griffin Mills',
      english_name: 'Morris Jast',
      age: 244,
      SSN: '78889545456124',
      email: 'your.email+fakedata68767@gmail.com',
      account: null,
      phone: '517-495-3333',
      nationality: null,
      religion: null,
      job: null,
      address: '4291 Bergstrom Forges',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 3,
      created_at: '2024-05-09T21:38:17.000000Z',
      updated_at: '2024-05-19T10:24:30.000000Z',
      login_type: 'students',
      payment: 'complete',
    },
    {
      id: 10,
      name: 'Muhammad Sanford',
      english_name: 'Johnnie Jenkins',
      age: 113,
      SSN: 'Fuga molestias quae.',
      email: 'your.email+fakedata87217@gmail.com',
      account: null,
      phone: '370-337-5991',
      nationality: null,
      religion: null,
      job: null,
      address: '71121 Huels Place',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 4,
      created_at: '2024-05-09T22:06:39.000000Z',
      updated_at: '2024-05-09T22:06:39.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 17,
      name: 'نتالاىبتبيبب',
      english_name: 'mohamed',
      age: 68,
      SSN: '50248257378346781',
      email: 'mmernax778@saykocak.com',
      account: null,
      phone: '556564655678',
      nationality: null,
      religion: null,
      job: null,
      address: 'hgjhgkk',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 3,
      created_at: '2024-05-10T00:17:26.000000Z',
      updated_at: '2024-05-10T00:17:26.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 18,
      name: 'Aubree Kihn',
      english_name: 'Autumn Stiedemann',
      age: 388,
      SSN: 'Eos nostrum porro.',
      email: 'your.email+fakedata22529@gmail.com',
      account: null,
      phone: '218-518-9163',
      nationality: null,
      religion: null,
      job: null,
      address: '683 Raymond Junctions',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 4,
      created_at: '2024-05-10T01:58:51.000000Z',
      updated_at: '2024-05-10T01:58:51.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 19,
      name: 'Christina Wilderman',
      english_name: 'Rowena Stroman',
      age: 407,
      SSN: 'Molestias natus necessitatibus aut soluta harum quia fugit ducimus reprehenderit.',
      email: 'your.email+fakedata19946@gmail.com',
      account: null,
      phone: '570-238-1492',
      nationality: null,
      religion: null,
      job: null,
      address: '759 Rosenbaum Key',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 4,
      created_at: '2024-05-10T02:03:40.000000Z',
      updated_at: '2024-05-10T02:03:40.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 20,
      name: 'Rosamond Ward',
      english_name: 'Arne Stanton',
      age: 68,
      SSN: 'Quas pariatur nesciunt debitis numquam repellat voluptate reprehenderit.',
      email: 'your.email+fakedata49271@gmail.com',
      account: null,
      phone: '682-900-5510',
      nationality: null,
      religion: null,
      job: null,
      address: '1505 Brakus Stream',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 2,
      created_at: '2024-05-10T02:05:00.000000Z',
      updated_at: '2024-05-10T02:05:00.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 21,
      name: "Madison O'Kon",
      english_name: 'Tamara Walsh',
      age: 309,
      SSN: 'Animi suscipit a numquam aut aliquam aut laboriosam.',
      email: 'your.email+fakedata30247@gmail.com',
      account: null,
      phone: '092-093-9138',
      nationality: null,
      religion: null,
      job: null,
      address: '94013 Ratke Place',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 3,
      created_at: '2024-05-10T02:06:48.000000Z',
      updated_at: '2024-05-10T02:06:48.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 22,
      name: 'Linnea Medhurst',
      english_name: 'Boyd Kunde',
      age: 222,
      SSN: 'Neque officiis id magni pariatur maiores quis neque.',
      email: 'your.email+fakedata87257@gmail.com',
      account: null,
      phone: '035-559-0959',
      nationality: null,
      religion: null,
      job: null,
      address: '366 Ebert Crescent',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 2,
      created_at: '2024-05-13T00:32:03.000000Z',
      updated_at: '2024-05-13T00:32:03.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 23,
      name: 'ahmed',
      english_name: 'jj',
      age: 5,
      SSN: '522222232',
      email: 'ahmedkhaledr2@gmail.com',
      account: null,
      phone: '46',
      nationality: null,
      religion: null,
      job: null,
      address: 'jb',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 2,
      created_at: '2024-05-19T11:55:02.000000Z',
      updated_at: '2024-05-19T11:55:02.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 24,
      name: 'ahmed',
      english_name: 'jjnnjbuhu',
      age: 23,
      SSN: '5222222322',
      email: 'aahmedkhaledr2@gmail.com',
      account: null,
      phone: '4622222222',
      nationality: null,
      religion: null,
      job: null,
      address: 'jbgygggyygy',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 2,
      created_at: '2024-05-19T11:59:30.000000Z',
      updated_at: '2024-05-19T11:59:30.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 25,
      name: 'ahmed',
      english_name: 'jjnnjbuhu',
      age: 23,
      SSN: '52222223224',
      email: 'aahmedkhaledrd2@gmail.com',
      account: null,
      phone: '4622222222',
      nationality: null,
      religion: null,
      job: null,
      address: 'jbgygggyygy',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 2,
      created_at: '2024-05-19T12:00:48.000000Z',
      updated_at: '2024-05-19T12:00:48.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 26,
      name: 'ahmed',
      english_name: 'jjnnjbuhu',
      age: 23,
      SSN: '522222232242',
      email: 'aaahmedkhaledrd2@gmail.com',
      account: null,
      phone: '4622222222',
      nationality: null,
      religion: null,
      job: null,
      address: 'jbgygggyygy',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 2,
      created_at: '2024-05-20T10:01:15.000000Z',
      updated_at: '2024-05-20T10:01:15.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 27,
      name: 'ahmed',
      english_name: 'jjnnjbuhu',
      age: 23,
      SSN: '5222222322422',
      email: 'aaaahmedkhaledrd2@gmail.com',
      account: null,
      phone: '4622222222',
      nationality: null,
      religion: null,
      job: null,
      address: 'jbgygggyygy',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 2,
      created_at: '2024-05-20T10:01:47.000000Z',
      updated_at: '2024-05-20T10:01:47.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 28,
      name: 'aaaaaaaaaaaaaa',
      english_name: 'aaaaaaaaaaa',
      age: 22,
      SSN: '122144455555',
      email: 'a@gmail.commm',
      account: null,
      phone: '74222222',
      nationality: null,
      religion: null,
      job: null,
      address: 'a',
      idea: 'a',
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 1,
      created_at: '2024-06-06T18:20:17.000000Z',
      updated_at: '2024-06-06T18:20:17.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 29,
      name: 'aaaaaaaaaaaaaa',
      english_name: 'aaaaaaaaaaa',
      age: 22,
      SSN: '122144455551',
      email: 'a@gmail.comm',
      account: null,
      phone: '74222222',
      nationality: null,
      religion: null,
      job: null,
      address: 'a',
      idea: 'a',
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 1,
      created_at: '2024-06-06T18:21:08.000000Z',
      updated_at: '2024-06-06T18:21:08.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 30,
      name: 'aaaaaaaaaaaaaa',
      english_name: 'aaaaaaaaaaa',
      age: 22,
      SSN: '122144455554',
      email: 'a@gmail.com',
      account: null,
      phone: '74222222',
      nationality: null,
      religion: null,
      job: null,
      address: 'a',
      idea: 'a',
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 1,
      created_at: '2024-06-06T18:32:39.000000Z',
      updated_at: '2024-06-06T18:32:39.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 31,
      name: 'aaaaaaaaaaaaaa',
      english_name: 'aaaaaaaaaaa',
      age: 22,
      SSN: '1221444555541',
      email: 'a@gmail.com1',
      account: null,
      phone: '74222222',
      nationality: null,
      religion: null,
      job: null,
      address: 'a',
      idea: 'a',
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 1,
      created_at: '2024-06-06T18:34:29.000000Z',
      updated_at: '2024-06-06T18:34:29.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 32,
      name: 'aaaaaaaaaaaaaa',
      english_name: 'aaaaaaaaaaa',
      age: 22,
      SSN: '122144455',
      email: 'a@gmail.com11',
      account: null,
      phone: '12221212',
      nationality: null,
      religion: null,
      job: null,
      address: 'a',
      idea: 'a',
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 1,
      created_at: '2024-06-11T00:34:33.000000Z',
      updated_at: '2024-06-11T00:34:33.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 34,
      name: 'aaaaaaaaaaaaaa',
      english_name: 'aaaaaaaaaaa',
      age: 22,
      SSN: '12214445561',
      email: 'toqa@gmail.com',
      account: null,
      phone: '12221212',
      nationality: null,
      religion: null,
      job: null,
      address: 'a',
      idea: 'a',
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 1,
      created_at: '2024-06-11T20:18:48.000000Z',
      updated_at: '2024-06-11T20:18:48.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 38,
      name: 'ahmed',
      english_name: 'ahmed',
      age: 21,
      SSN: '30210261400579',
      email: 'ahmedkhaledr2@gmail.com3333',
      account: null,
      phone: '01017477073',
      nationality: null,
      religion: null,
      job: null,
      address: 'anything',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 1,
      created_at: '2024-06-13T02:28:59.000000Z',
      updated_at: '2024-06-13T02:28:59.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 39,
      name: 'ahmed',
      english_name: 'ahmed',
      age: 21,
      SSN: '30210261400578',
      email: 'ahmedkhaledr2@gmail.com33333',
      account: null,
      phone: '01017477073',
      nationality: null,
      religion: null,
      job: null,
      address: 'anything',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 1,
      created_at: '2024-06-13T09:32:32.000000Z',
      updated_at: '2024-06-13T09:32:32.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 40,
      name: 'ahmed',
      english_name: 'ahmed',
      age: 21,
      SSN: '30210261400577',
      email: 'ahmedkhaledr2@gmail.com333335',
      account: null,
      phone: '01017477073',
      nationality: null,
      religion: null,
      job: null,
      address: 'anything',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 1,
      created_at: '2024-06-13T09:37:50.000000Z',
      updated_at: '2024-06-13T09:37:50.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 41,
      name: 'ahmed',
      english_name: 'ahmed',
      age: 21,
      SSN: '302102614005779',
      email: 'ahmedkhaledr2@gmail.com3333350',
      account: null,
      phone: '01017477073',
      nationality: null,
      religion: null,
      job: null,
      address: 'anything',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 1,
      created_at: '2024-06-13T09:39:52.000000Z',
      updated_at: '2024-06-13T09:39:52.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 42,
      name: 'Jeanie Nicolas',
      english_name: 'Thelma Runolfsdottir',
      age: 40,
      SSN: 'Tempore voluptatibus recusandae nemo molestias nisi quia.',
      email: 'your.email+fakedata11716@gmail.com',
      account: null,
      phone: '036-473-0823',
      nationality: null,
      religion: null,
      job: null,
      address: '20208 Van Causeway',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 4,
      created_at: '2024-06-14T23:35:28.000000Z',
      updated_at: '2024-06-14T23:35:28.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 43,
      name: 'Jeanie Nicolas',
      english_name: 'Thelma Runolfsdottir',
      age: 40,
      SSN: 'Tempccore voluptatibus recusandae nemo molestias nisi quia.',
      email: 'your.email+fakedaxxxxxta11716@gmail.com',
      account: null,
      phone: '036-473-0823',
      nationality: null,
      religion: null,
      job: null,
      address: '20208 Van Causeway',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 4,
      created_at: '2024-06-14T23:42:02.000000Z',
      updated_at: '2024-06-14T23:42:02.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 44,
      name: 'Jacky Emmerich',
      english_name: 'Benjamin Roberts',
      age: 106,
      SSN: 'Nostrum eveniet illo dolorum.',
      email: 'your.email+fakedata82630@gmail.com',
      account: null,
      phone: '725-276-7495',
      nationality: null,
      religion: null,
      job: null,
      address: '392 Nicola Villages',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 2,
      created_at: '2024-06-14T23:58:38.000000Z',
      updated_at: '2024-06-14T23:58:38.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 45,
      name: 'Jess Wuckert',
      english_name: 'Erna Conroy',
      age: 506,
      SSN: 'Delectus recusandae nisi maiores amet nemo consectetur.',
      email: 'your.email+fakedata22886@gmail.com',
      account: null,
      phone: '685-074-5901',
      nationality: null,
      religion: null,
      job: null,
      address: '60573 Erdman Ville',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 2,
      created_at: '2024-06-15T00:02:42.000000Z',
      updated_at: '2024-06-15T00:02:42.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 46,
      name: 'Pearl Prosacco',
      english_name: 'Aiyana Weber',
      age: 517,
      SSN: 'Suscipit numquam itaque deserunt recusandae.',
      email: 'your.email+fakedata26243@gmail.com',
      account: null,
      phone: '455-017-9573',
      nationality: null,
      religion: null,
      job: null,
      address: '260 Kayli Avenue',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 3,
      created_at: '2024-06-15T00:45:27.000000Z',
      updated_at: '2024-06-15T00:45:27.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 47,
      name: 'Jacklyn Kerluke',
      english_name: 'Hattie Jacobs',
      age: 555,
      SSN: 'Accusantium ad odio sapiente nobis accusantium reiciendis alias temporibus tempor89ibus.',
      email: 'your.email+fakedata8288957@gmail.com',
      account: null,
      phone: '735-629-4479',
      nationality: null,
      religion: null,
      job: null,
      address: '533 Monahan Forest',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 4,
      created_at: '2024-06-15T01:56:52.000000Z',
      updated_at: '2024-06-15T01:56:52.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 48,
      name: 'Reid Casper',
      english_name: 'Keyshawn Berge',
      age: 423,
      SSN: 'Natus in laudantium cum odit possisssmus.',
      email: 'your.email+fakedata25007899@gmail.com',
      account: null,
      phone: '912-860-1089',
      nationality: null,
      religion: null,
      job: null,
      address: '2160 Anya Mews',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 3,
      created_at: '2024-06-15T02:05:04.000000Z',
      updated_at: '2024-06-15T02:05:04.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 49,
      name: 'Bradly Cummings',
      english_name: 'Sherman Hegmann',
      age: 589,
      SSN: '0157896412358erv',
      email: 'your.email+fakedata4078601r@gmail.com',
      account: null,
      phone: '761-711-0853',
      nationality: null,
      religion: null,
      job: null,
      address: '99229 Justus Shoals',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 3,
      created_at: '2024-06-15T02:09:41.000000Z',
      updated_at: '2024-06-15T02:09:41.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 50,
      name: 'Rose Fay',
      english_name: 'Frankie Kub',
      age: 387,
      SSN: 'Dicta quaerat neque reprehenderit odio mcxcxxcagnam.',
      email: 'your.email+fakedata9689xccxx1@gmail.com',
      account: null,
      phone: '635-465-4247',
      nationality: null,
      religion: null,
      job: null,
      address: '6872 Horace Brook',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 3,
      created_at: '2024-06-15T02:13:03.000000Z',
      updated_at: '2024-06-15T02:13:03.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 51,
      name: 'Glenna Batz',
      english_name: 'Kira Goyette',
      age: 175,
      SSN: '7896325410458714',
      email: 'your.email+fakedata809600@gmail.com',
      account: null,
      phone: '074-429-9993',
      nationality: null,
      religion: null,
      job: null,
      address: '6469 Von Parks',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 3,
      created_at: '2024-06-15T02:14:48.000000Z',
      updated_at: '2024-06-15T02:14:48.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 53,
      name: 'Brice Parisian',
      english_name: 'Ashtyn Casper',
      age: 455,
      SSN: '789632541589632',
      email: 'your.email+fakedata34140we789@gmail.com',
      account: null,
      phone: '988-565-1610',
      nationality: null,
      religion: null,
      job: null,
      address: '3076 Heathcote Brook',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 3,
      created_at: '2024-06-15T02:19:54.000000Z',
      updated_at: '2024-06-15T02:19:54.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 56,
      name: 'Jonathon Dickens',
      english_name: 'Emory Stracke',
      age: 143,
      SSN: 'Necessitatibus quibusdam unde ea ut tempore recusandae7895 suscipit.',
      email: 'your.email+fakedata55787789654@gmail.com',
      account: null,
      phone: '044-296-3263',
      nationality: null,
      religion: null,
      job: null,
      address: '4055 Ebert Dale',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 2,
      created_at: '2024-06-15T02:24:34.000000Z',
      updated_at: '2024-06-15T02:24:34.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 58,
      name: 'Angie Graham',
      english_name: 'Kyra Lockman',
      age: 356,
      SSN: '789654789654123',
      email: 'your.email+fakedata76700054@gmail.com',
      account: null,
      phone: '344-991-7611',
      nationality: null,
      religion: null,
      job: null,
      address: '671 Bailey Oval',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 4,
      created_at: '2024-06-16T11:34:55.000000Z',
      updated_at: '2024-06-16T11:34:55.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 59,
      name: 'Angie Graham',
      english_name: 'Kyra Lockman',
      age: 356,
      SSN: '789654789654124',
      email: 'kreep@gmail.com',
      account: null,
      phone: '344-991-7611',
      nationality: null,
      religion: null,
      job: null,
      address: '671 Bailey Oval',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 4,
      created_at: '2024-06-16T19:48:51.000000Z',
      updated_at: '2024-06-16T19:48:51.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 60,
      name: 'Angie Graham',
      english_name: 'Kyra Lockman',
      age: 356,
      SSN: '7896547896541239',
      email: 'your.email+fakedata76700054a@gmail.com',
      account: null,
      phone: '344-991-7611',
      nationality: null,
      religion: null,
      job: null,
      address: '671 Bailey Oval',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 4,
      created_at: '2024-06-16T19:50:29.000000Z',
      updated_at: '2024-06-16T19:50:29.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
    {
      id: 62,
      name: 'محمد علاء الدين سعيد',
      english_name: 'mohamed AlaaEldein said',
      age: 418,
      SSN: '01234567891112',
      email: 'mohamed3laa3467@gmail.com',
      account: null,
      phone: '762-951-1231',
      nationality: null,
      religion: null,
      job: null,
      address: '9368 Schaefer Drive',
      idea: null,
      type: 'external',
      degree: 'master',
      level: 'first_level',
      enrollment_papers: null,
      original_bachelors_degree: null,
      status: 'pending',
      time: 'first',
      marital_status: 'married',
      gender: 'male',
      department_id: 1,
      created_at: '2024-06-18T09:57:20.000000Z',
      updated_at: '2024-06-18T09:57:20.000000Z',
      login_type: 'students',
      payment: 'pending',
    },
  ]);
  // const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const dispatch = useDispatch();
  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await axios.get(`${URLng}/PendfdingStudent`, {
          headers: {
            Accept: 'application/json',
          },
        });
        console.log(response);
        // setRows(JSON.parse(response.data));
        console.log(response.data);
        setLoading(false);
      } catch (error) {
        setError(error);
        setLoading(false);
      }
    };

    fetchData();
  }, []);
  const sendRegEmail = (name, studentEmail) => {
    const templateParams = {
      to_name: name,
      to_email: studentEmail,
    };

    emailjs
      .send(
        'service_uezy399',
        'template_3jxv9bp',
        templateParams,
        'jhDDp8FmE6Tr9F8e5'
      )
      .then(
        (response) => {
          console.log('SUCCESS!', response.status, response.text);
        },
        (err) => {
          console.log('FAILED...', err);
        }
      );
  };
  const sendAcceptEmail = (
    name,
    studentEmail,
    studentAccount,
    studentPassword
  ) => {
    const templateParams = {
      to_name: name,
      to_email: studentEmail,
      account: studentAccount,
      password: studentPassword,
    };
    emailjs
      .send(
        'service_uezy399',
        'template_2nhp9hl',
        templateParams,
        'jhDDp8FmE6Tr9F8e5'
      )
      .then(
        (response) => {
          console.log('SUCCESS!', response.status, response.text);
        },
        (err) => {
          console.log('FAILED...', err);
        }
      );
  };

  const handleAccept = async ({ id, email, name }) => {
    try {
      const res = await axios.post(`${URLng}/addacount/${id}`);
      setRows((prevRows) => prevRows.filter((row) => row.id !== id));
      console.log(res.data);
      sendAcceptEmail(name, email, res.data.account, res.data.password);
      dispatch(accpeting(true));
      dispatch(registering(false));
    } catch (error) {
      console.error(`Error accepting student with id: ${id}`, error);
    }
  };

  const handleReject = async ({ id, name, email }) => {
    try {
      await axios.post(`${URLng}/rejectstudent/${id}`);
      setRows((prevRows) => prevRows.filter((row) => row.id !== id));
      sendRegEmail(name, email);
      dispatch(accpeting(false));
      dispatch(registering(false));
    } catch (error) {
      console.error(`Error rejecting student with id: ${id}`, error);
    }
  };

  const columns = [
    { field: 'id', headerName: 'ID', width: 90 },
    { field: 'name', headerName: 'Name', width: 110 },
    { field: 'english_name', headerName: 'English Name', width: 110 },
    { field: 'nationality', headerName: 'Nationality', width: 110 },
    { field: 'religion', headerName: 'Religion', width: 110 },
    { field: 'job', headerName: 'Job', width: 110 },
    { field: 'age', headerName: 'Age', width: 110 },
    { field: 'SSN', headerName: 'SSN', width: 110 },
    { field: 'phone', headerName: 'Phone', width: 110 },
    { field: 'address', headerName: 'Address', width: 110 },
    { field: 'department', headerName: 'Department', width: 110 },
    { field: 'gender', headerName: 'Gender', width: 110 },
    { field: 'email', headerName: 'Email', width: 110 },
    {
      field: 'original_bachelors_degree',
      headerName: "Original Bachelor's Degree",
      width: 300,
      renderCell: (params) => (
        <div className="flex items-center justify-center">
          <a
            href={params.value ? params.value : '#'}
            target="_blank"
            rel="noopener noreferrer"
          >
            {params.value ? 'file' : 'no file'}
          </a>
        </div>
      ),
    },
    {
      field: 'enrollment_papers',
      headerName: 'Enrollment Papers',
      width: 300,
      renderCell: (params) => (
        <div className="flex items-center justify-around gap-3">
          {Array.isArray(params.value)
            ? params.value.map((file, index) => (
                <a
                  key={index}
                  href={file}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {`file${index + 1}`}
                </a>
              ))
            : 'no file'}
        </div>
      ),
    },
    {
      field: 'actions',
      headerName: 'Actions',
      width: 200,
      renderCell: (params) => (
        <div className="flex gap-7">
          <Button
            variant="contained"
            color="primary"
            size="small"
            style={{ marginRight: 8 }}
            onClick={() => handleAccept(params.row)}
          >
            قبول
          </Button>
          <Button
            variant="contained"
            color="secondary"
            size="small"
            onClick={() => handleReject(params.row)}
          >
            رفض
          </Button>
        </div>
      ),
    },
  ];

  if (loading) {
    return (
      <div className="flex items-center justify-center">
        <ClipLoader size={150} color="#123abc" loading={loading} />
      </div>
    );
  }

  if (error) {
    return <div>Error: {error.message}</div>;
  }

  return (
    <div className="overflow-hidden">
      <MainLayout title={'Accept Student and Make ACC'}>
        <Box sx={{ height: 400, width: '200%' }}>
          <DataGrid
            rows={rows}
            columns={columns}
            pageSize={5}
            rowsPerPageOptions={[5]}
            checkboxSelection
            autoHeight
            getRowId={(row) => row.id}
            sx={{
              '& .MuiDataGrid-root': {
                overflowX: 'auto',
              },
              '& .MuiDataGrid-columnHeaders': {
                backgroundColor: 'rgba(255, 255, 255, 0.8)',
              },
            }}
          />
          <div className="flex items-center justify-center m-5 p-10">
            <button className="main-btn w-96">Accept All</button>
          </div>
        </Box>
      </MainLayout>
    </div>
  );
}

export default AcceptStudent;
